name: E2E Test - vSphere Management Cluster

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  e2e-vsphere-management-cluster-test:
    name: E2E vSphere Management Cluster Test
    runs-on: vsphere-e2e-runner
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run vSphere Management Cluster E2E Test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_E2E_ACCESS_TOKEN }}
          MANAGEMENT_CLUSTER_VSPHERE_CONTROL_PLANE_ENDPOINT: ${{ secrets.MANAGEMENT_CLUSTER_VSPHERE_CONTROL_PLANE_ENDPOINT }}
          WORKLOAD_CLUSTER_VSPHERE_CONTROL_PLANE_ENDPOINT: ${{ secrets.WORKLOAD_CLUSTER_VSPHERE_CONTROL_PLANE_ENDPOINT }}
          VSPHERE_SERVER: ${{ secrets.VSPHERE_SERVER }}
          VSPHERE_SSH_AUTHORIZED_KEY: ${{ secrets.VSPHERE_SSH_AUTHORIZED_KEY }}
          VSPHERE_USERNAME: ${{ secrets.VSPHERE_USERNAME }}
          VSPHERE_PASSWORD: ${{ secrets.VSPHERE_PASSWORD }}
          VSPHERE_DATACENTER: ${{ secrets.VSPHERE_DATACENTER }}
          VSPHERE_DATASTORE: ${{ secrets.VSPHERE_DATASTORE }}
          VSPHERE_FOLDER: ${{ secrets.VSPHERE_FOLDER }}
          VSPHERE_NETWORK: ${{ secrets.VSPHERE_NETWORK }}
          VSPHERE_RESOURCE_POOL: ${{ secrets.VSPHERE_RESOURCE_POOL }}
        run: |
          # Workaround for issue https://github.com/kubernetes-sigs/kind/issues/2240
          sudo sysctl net/netfilter/nf_conntrack_max=131072

          make vsphere-management-cluster-e2e-test
